<template>
  <div class="banner-content" style="width: 100%; justify-content: center; display: flex;">
    <ContentBanner :title="banner.title" :description="banner.description" :buttonText="banner.buttonText"
      @buttonClicked="openExecutionComponent()" />
  </div>


  


  <v-container style="display: flex; justify-content: center; flex-direction: column;">
    <div class="text-center py-16">
      <h2>Why use Massa?</h2>
      <p>See the advantages of using the Massa Algoritm</p>
    </div>
    <v-row>
      <v-col class="pa-12" v-for="item in items" cols="4" style="width: 100%; display: flex; justify-content: center;">
        <v-btn variant="text" size="140" :prepend-icon="item.icon" :ripple="false" stacked :readonly="true"
          @click="selectCategory(item.category)">
          {{ item.text }}
          <p class="text-subtitle-2" style="margin-top: 0.5rem;">{{ item.subtext }}</p>
        </v-btn>
      </v-col>
    </v-row>
  </v-container>


  <div class="banner2" style="width: 100%; justify-content: center; display: flex;" >
    <ContentBanner :title="banner2.title" :description="banner2.description" />
  </div>


  <div class="panel">
    <v-expansion-panels variant="accordion" style="width: 100%; display: flex; justify-content: center;">
      <v-expansion-panel v-for="dropdownValue in dropdownValues" :key="dropdownValue.position">
        <v-expansion-panel-title>{{ dropdownValue.title }}</v-expansion-panel-title>
        <v-expansion-panel-text v-html="dropdownValue.text" style="display: flex; flex-direction: column;"></v-expansion-panel-text>
      </v-expansion-panel>
    </v-expansion-panels>
  </div>


  <div class="banner3" style="width: 100%; justify-content: center; display: flex;">
    <ContentBanner :title="banner3.title" :description="banner3.description" :buttonText="banner3.buttonText"
      @buttonClicked="openTutorialComponent()" />
  </div>

</template>

<script setup>
import ContentBanner from '@/components/ContentBanner.vue';
import { useRouter } from 'vue-router';

const router = useRouter();

const banner = {
  title: "Welcome to the Massa",
  description: "Building Predictive QSAR models with Rational Sampling",
  buttonText: "RUN ALGORITHM",
};

const banner2 = {
  title: "How the algorithm works",
  description: "The MASSA Algorithm explores the biological, physicochemical, and structural spaces of molecules using PCA, HCA, and K-modes to ensure equal representation of the dataset's diversity in the training and test sets. The tool is completely free, and we only request that users cite the article https://doi.org/10.1007/s10822-023-00536-y and the specific interface they used (for the web version, please cite this website; for the command-line version, please cite the GitHub repository at https://github.com/gcverissimo/MASSA_Algorithm).",
};

const banner3 = {
  title: "Still in doubt?",
  description: "See the tutorial on how to use the Algorithm",
  buttonText: "TUTORIAL",
};

const items = [
  {
    category: 'massa',
    text: 'Massa',
    subtext: 'Prepare datasets for generating prediction models in cheminformatics.',
    icon: 'mdi-atom',
  },
  {
    category: 'results',
    text: 'Results',
    subtext: 'Get interactively plotted data and download it as a PDF',
    icon: 'mdi-chart-line',
  },
  {
    category: 'security',
    text: 'Security',
    subtext: 'Only anonymized data is securely stored for statistical purposes',
    icon: 'mdi-shield-check',
  },
  {
    category: 'technicalSupport',
    text: 'Technical Support',
    subtext: 'Visit the tutorial page for guidance or contact us via email for further assistance.',
    icon: 'mdi-headset',
  },
  {
    category: 'data',
    text: 'Data',
    subtext: 'Explore global analysis statistics and user origin insights through interactive visuals.',
    icon: 'mdi-cloud-upload',
  },
  {
    category: 'documentation',
    text: 'Documentation',
    subtext: 'Access detailed guides and resources to support your analysis',
    icon: 'mdi-file-document-outline',
  },
];

const dropdownValues = [
{
    title: 'Upload your Data',
    text: `<p style="margin: 15px">1. The MASSA Algorithm accepts input files in the formats: <strong>.sdf</strong>, <strong>.mol</strong>, <strong>.mol2</strong>, <strong>.xlsx</strong>, <strong>.xls</strong>, and <strong>.csv</strong>. However, the <strong>.sdf</strong> format is preferred.</p>

    <p style="margin-left: 15px; margin-right: 15px;"><strong>Notes:</strong></p>
    <ol type="a" style="margin-left: 15px; margin-right: 15px;">
      <li style="margin-left: 15px; margin-right: 15px;"><strong>.mol2</strong> files have limitations in storing molecular properties and follow different saving patterns. Due to this, we only support .mol2 files that are generated by Discovery Studio Visualizer.</li>
      <li style="margin-left: 15px; margin-right: 15px;">For <strong>.xlsx</strong>, <strong>.xls</strong>, and <strong>.csv</strong>:
        <ol type="i" style="margin-left: 15px; margin-right: 15px;">
          <li>MASSA will look for a column with "smiles" in the name and use it as the source of input molecules.</li>
          <li>MASSA will look for a column with one of the following names in the priority order: "Molecule name", "Name", "Molecule ChEMBL ID", or "ID". If none of these columns are found, it will use the molecule index.</li>
        </ol>
      </li>
    </ol>`
  },
  {
    title: 'Smart Sampling',
    text: `<p style="margin: 15px"> 2. The MASSA Algorithm is a Python script designed to calculate physicochemical properties (such as HBA, HBD, MW, nRotB, Fsp3, TPSA, and log P) and structural properties, including Atom-Pair fingerprints, for molecules provided in a specified file format (see the section “Upload your data”). Using HCA, it independently clusters each of the two domains (physicochemical and structural properties) along with the domain linked to biological activities. These initial cluster labels are then combined through K-modes clustering, producing a unified cluster division that guides the rational sampling of the molecules. </p>`
  },
  {
    title: 'Enhanced QSAR Modeling',
    text: `<p style="margin-left: 15px; margin-right: 15px;">3. a. Our results indicate that machine learning and QSAR models developed with MASSA-generated datasets achieve superior performance compared to those generated using random sampling or other rational sampling methods, including the Kennard-Stone algorithm, SPXY, and Sphere Exclusion, as assessed by internal and external validation metrics. For further details, we invite you to read our article and kindly request that you cite our <a href="https://doi.org/10.1007/s10822-023-00536-y" target="_blank">work</a>.</p>  
    <p style="margin-left: 15px; margin-right: 15px;"> b.	If local dataset processing is required, we are pleased to provide a command-line tool for this purpose, accessible <a href="https://github.com/gcverissimo/MASSA_Algorithm" target="_blank">here</a>.</p>`
  },
  {
    title: 'Download your Results',
    text: `<p style="margin-left: 15px; margin-right: 15px;"> 4. a.	Finally, in addition to an output ".sdf" file with the sampled dataset, the tool generates visualizations of the division, including bar plots, dendrograms, and line plots. A final report is also provided, containing the images and the percentage of molecules in each cluster.</p> 
    <p style="margin-left: 15px; margin-right: 15px;">b.	Please remember that we kindly request users to cite our <a href="https://doi.org/10.1007/s10822-023-00536-y" target="_blank">work</a> if they use the tool.</p>`
  },
  {
    title: 'Cite the tool',
    text: `<p style="margin: 15px"> 5.	As part of the terms of use, whenever you use the tool, you must cite the article and the interface you used (either the graphical interface of the web version or the command-line interface, available on GitHub, for local use). Below, we provide citation templates in American Chemical Society format for references:'</p>
    <ol type="i" style="margin-left: 15px; margin-right: 15px;">
      <li style="margin-left: 15px; margin-right: 15px;">Article (always cite): Veríssimo, G. C.; Pantaleão, S. Q.; Fernandes, P. de O.; Gertrudes, J. C.; Kronenberger, T.; Honorio, K. M.; Maltarollo, V. G. MASSA Algorithm: An Automated Rational Sampling of Training and Test Subsets for QSAR Modeling. J. Comput. Aided Mol. Des. 2023, 37 (12), 735–754. <a href="https://doi.org/10.1007/s10822-023-00536-y" target="_blank">DOI</a></li>
      <li style="margin-left: 16px; margin-right: 15px;">GUI – Web version: Machado, D. G. S.; Ferreira, G. R.; Braga, J. P. S.; Sales, J. V. R.; Randazzo, L. MASSA Algorithm web interface, Belo Horizonte, 2025. <a href="https://massa-web.netlify.app/" target="_blank">MASSA Web</a></li>
      <li style="margin-left: 17px; margin-right: 15px;">CLI – Local version: Veríssimo, G. C. MASSA Algorithm: version 0.9.5, UFMG: Belo Horizonte, 2024. <a href="https://github.com/gcverissimo/MASSA_Algorithm" target="_blank">GitHub</a></li>
    </ol>`
  }
];

function openExecutionComponent() {
  router.push('/execution');
};

function openTutorialComponent() {
  router.push('/support');
};
</script>

<style>
.sub-text {
  font-size: 1.4rem;
  margin-bottom: 2rem;
}

.banner2 {
  margin-top: 5rem;
}

.panel {
  margin: 5rem;
}
</style>