
class DefaultArgumentValues:
    DEFAULT_PERCENTAGE_OF_MOLECULES = 0.8
    DEFAULT_NUMBER_OF_PCS = 0.85
    DEFAULT_FONT_FOR_X_AXIS_OF_DENDROGRAMS = 5
    DEFAULT_FONT_FOR_X_AXIS_OF_BAR_PLOTS = 12
    DEFAULT_LINKAGE_METHOD = "complete"
    DEFAULT_IMAGE_EXTENSION_TYPE = "png"